name: Dependency Updates

on:
  schedule:
    # Run every Monday at 8 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Check for npm updates
      run: |
        echo "📦 Checking for npm package updates..."
        npm outdated || true
        
        # Check if updates are available
        if npm outdated --json | grep -q '"current"'; then
          echo "updates_available=true" >> $GITHUB_ENV
          echo "📋 Updates are available"
        else
          echo "updates_available=false" >> $GITHUB_ENV
          echo "✅ All packages are up to date"
        fi
    
    - name: Update dependencies
      if: env.updates_available == 'true'
      run: |
        echo "🔄 Updating npm dependencies..."
        npm update
        
        # Test build after updates
        npm run build
        
        # Test Docker build
        docker build -f Dockerfile.simple -t test-update .
    
    - name: Create Pull Request
      if: env.updates_available == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: '🤖 Update npm dependencies'
        title: '🤖 Automated dependency updates'
        body: |
          ## 🤖 Automated Dependency Updates
          
          This PR contains automated updates to npm dependencies.
          
          ### Changes
          - Updated npm packages to latest versions
          - Verified build process still works
          - Tested Docker container build
          
          ### Testing
          - [x] SASS compilation successful
          - [x] Docker build successful
          - [ ] Manual testing required
          
          Please review the changes and test thoroughly before merging.
          
          ---
          *This PR was created automatically by GitHub Actions*
        branch: automated-dependency-updates
        delete-branch: true